version: '3.7'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080:8080"
    volumes:
      - ./searxng-data:/etc/searxng:ro
